### ISSUE TITLE
debugging conection was closed

### ISSUE THREAD

**Issue by punisher8499** [FWSmasher/rigtools#5]
![Screenshot 2024-09-28 1 24 42 AM](https://github.com/user-attachments/assets/dd522519-0921-41bf-bd95-abee7e7582ba)

**Comment by sadgimkitgamer** [comment]
idk what happened, it worked the first few times

**Comment by FunnyCorgi** [comment]
@sadblooketgamer @punisher8499 You have the web socket set to `*websocket%20url*` . This isn't a valid url, and it can be fixed by providing a valid host for the RigTools websocket instead of that.

The `*websocket%20url*` in the instructions is a placeholder, you need to replace it with a real url.

**Comment by FunnyCorgi** [comment]
By the way, %20 is the thing for spaces. It is where the space is in the instruction url.

**Comment by MunyDev** [comment]
Url is most likely blocked, use another URL, or perform it at home.
